# Site settings
# in the templates available like {{ site.myvariable }}.
title: Chenlu's Blog
email: wnarry1996@gmail.com
brand: Chenlu Wang
headline: Inventor, Engineer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "https://wnarrylu.github.io/chenluwang.github.io/" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: wnarry1996@gmail.com
phone: +1-202-655-0670

# Tracking
googleAnalitycsID: UA-83933844-1

